/**
 * Constants for booking form dropdowns
 * Per BOOKING_FLOW.md – DOCUMENT_CODES, COUNTRIES, US_STATES, MEXICAN_STATES, TRAVELER_STATUSES
 */

export const DOCUMENT_CODES = [
  { value: "P", label: "P - PASSPORT" },
  { value: "DL", label: "DL - DRIVER LICENSE" },
  { value: "ID", label: "ID - ENHANCED DRIVER'S LICENSE (EDL)" },
  { value: "A", label: "A - U.S. ALIEN REGISTRATION CARD" },
  { value: "C", label: "C - PERMANENT RESIDENT CARD" },
  { value: "FB", label: "FB - BIRTH CERTIFICATE" },
  { value: "VB", label: "VB - LASER VISA - BCC" },
  { value: "VN", label: "VN - VISA NON-IMMIGRANT" },
  { value: "VI", label: "VI - VISA IMMIGRANT" },
  { value: "IP", label: "IP - U.S. PASSPORT CARD" },
  { value: "IG", label: "IG - GLOBAL ENTRY CARD" },
  { value: "IN", label: "IN - NEXUS CARD" },
  { value: "IS", label: "IS - SENTRI CARD" },
  { value: "IF", label: "IF - FAST CARD" },
  { value: "FD", label: "FD - FACILITATION DOCUMENT" },
  { value: "MG", label: "MG - MILITARY ID DOCUMENT" },
  { value: "MD", label: "MD - U.S. MERCHANT MARINER DOCUMENT" },
  { value: "MC", label: "MC - FOREIGN MARINER DOCUMENT" },
  { value: "N", label: "N - NATURALIZATION CERTIFICATE" },
  { value: "ND", label: "ND - NATIVE AMERICAN INDIAN/INAC" },
  { value: "TR", label: "TR - DHS RE-ENTRY PERMIT" },
  { value: "TP", label: "TP - DHS REFUGEE TRAVEL DOCUMENT" },
  { value: "PRU", label: "PRU - REENTRY PERMIT (BEGINNING 2009)" },
  { value: "PTU", label: "PTU - REFUGEE TRAVEL (BEGINNING 2009)" },
] as const;

export const US_STATES = [
  { value: "AL", label: "AL - ALABAMA" },
  { value: "AK", label: "AK - ALASKA" },
  { value: "AZ", label: "AZ - ARIZONA" },
  { value: "AR", label: "AR - ARKANSAS" },
  { value: "CA", label: "CA - CALIFORNIA" },
  { value: "CO", label: "CO - COLORADO" },
  { value: "CT", label: "CT - CONNECTICUT" },
  { value: "DE", label: "DE - DELAWARE" },
  { value: "DC", label: "DC - DISTRICT OF COLUMBIA" },
  { value: "FL", label: "FL - FLORIDA" },
  { value: "GA", label: "GA - GEORGIA" },
  { value: "HI", label: "HI - HAWAII" },
  { value: "IL", label: "IL - ILLINOIS" },
  { value: "IN", label: "IN - INDIANA" },
  { value: "IA", label: "IA - IOWA" },
  { value: "KS", label: "KS - KANSAS" },
  { value: "KY", label: "KY - KENTUCKY" },
  { value: "LA", label: "LA - LOUISIANA" },
  { value: "ME", label: "ME - MAINE" },
  { value: "MD", label: "MD - MARYLAND" },
  { value: "MA", label: "MA - MASSACHUSETTS" },
  { value: "MI", label: "MI - MICHIGAN" },
  { value: "MN", label: "MN - MINNESOTA" },
  { value: "MS", label: "MS - MISSISSIPPI" },
  { value: "MO", label: "MO - MISSOURI" },
  { value: "MT", label: "MT - MONTANA" },
  { value: "NE", label: "NE - NEBRASKA" },
  { value: "NV", label: "NV - NEVADA" },
  { value: "NH", label: "NH - NEW HAMPSHIRE" },
  { value: "NJ", label: "NJ - NEW JERSEY" },
  { value: "NM", label: "NM - NEW MEXICO" },
  { value: "NY", label: "NY - NEW YORK" },
  { value: "NC", label: "NC - NORTH CAROLINA" },
  { value: "ND", label: "ND - NORTH DAKOTA" },
  { value: "OH", label: "OH - OHIO" },
  { value: "OK", label: "OK - OKLAHOMA" },
  { value: "OR", label: "OR - OREGON" },
  { value: "PA", label: "PA - PENNSYLVANIA" },
  { value: "RI", label: "RI - RHODE ISLAND" },
  { value: "SC", label: "SC - SOUTH CAROLINA" },
  { value: "SD", label: "SD - SOUTH DAKOTA" },
  { value: "TN", label: "TN - TENNESSEE" },
  { value: "TX", label: "TX - TEXAS" },
  { value: "UT", label: "UT - UTAH" },
  { value: "VT", label: "VT - VERMONT" },
  { value: "VA", label: "VA - VIRGINIA" },
  { value: "WA", label: "WA - WASHINGTON" },
  { value: "WV", label: "WV - WEST VIRGINIA" },
  { value: "WI", label: "WI - WISCONSIN" },
  { value: "WY", label: "WY - WYOMING" },
] as const;

export const MEXICAN_STATES = [
  { value: "BC", label: "BC - BAJA CALIFORNIA" },
  { value: "BCS", label: "BCS - BAJA CALIFORNIA SUR" },
  { value: "Camp", label: "Camp - CAMPECHE" },
  { value: "Chis", label: "Chis - CHIAPAS" },
  { value: "Chih", label: "Chih - CHIHUAHUA" },
  { value: "Coah", label: "Coah - COAHUILA" },
  { value: "Dgo", label: "Dgo - DURANGO" },
  { value: "Gto", label: "Gto - GUANAJUATO" },
  { value: "Jal", label: "Jal - JALISCO" },
  { value: "MEX", label: "MEX - MÉXICO" },
  { value: "Mich", label: "Mich - MICHOACÁN" },
  { value: "NL", label: "NL - NUEVO LEÓN" },
  { value: "Oax", label: "Oax - OAXACA" },
  { value: "Pue", label: "Pue - PUEBLA" },
  { value: "QR", label: "QR - QUINTANA ROO" },
  { value: "Sin", label: "Sin - SINALOA" },
  { value: "Son", label: "Son - SONORA" },
  { value: "Tamps", label: "Tamps - TAMAULIPAS" },
  { value: "Ver", label: "Ver - VERACRUZ" },
  { value: "Yuc", label: "Yuc - YUCATÁN" },
] as const;

export const MIXED_STATES = [
  ...MEXICAN_STATES,
  ...US_STATES,
] as const;

export const COUNTRIES = [
  { value: "USA", label: "UNITED STATES - USA" },
  { value: "MEX", label: "MEXICO - MEX" },
  { value: "CAN", label: "CANADA - CAN" },
  { value: "GBR", label: "UNITED KINGDOM - GBR" },
  { value: "FRA", label: "FRANCE - FRA" },
  { value: "DEU", label: "GERMANY - DEU" },
  { value: "ESP", label: "SPAIN - ESP" },
  { value: "ITA", label: "ITALY - ITA" },
  { value: "CHN", label: "CHINA - CHN" },
  { value: "JPN", label: "JAPAN - JPN" },
  { value: "IND", label: "INDIA - IND" },
  { value: "BRA", label: "BRAZIL - BRA" },
  { value: "COL", label: "COLOMBIA - COL" },
  { value: "ARG", label: "ARGENTINA - ARG" },
  { value: "PHL", label: "PHILIPPINES - PHL" },
  { value: "PAK", label: "PAKISTAN - PAK" },
  { value: "BGD", label: "BANGLADESH - BGD" },
  { value: "NGA", label: "NIGERIA - NGA" },
  { value: "RUS", label: "RUSSIA - RUS" },
  { value: "XXX", label: "UNKNOWN - XXX" },
] as const;

export const TRAVELER_STATUSES = [
  { value: "FL", label: "FL - Passenger" },
  { value: "FM", label: "FM - Crew" },
] as const;

export const GENDERS = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer_not_say", label: "Prefer not to say" },
] as const;
